#ifndef __LWIPOPTS_H__
#define __LWIPOPTS_H__

#define NO_SYS 1
#define SYS_LIGHTWEIGHT_PROT 0
#define LWIP_SOCKET 0
#define LWIP_NETCONN 0
#define LWIP_TCPIP_CORE_LOCKING 0
#define LWIP_COMPAT_MUTEX 1
#define LWIP_HAVE_LOOPIF 0

#define LWIP_IPV4 1
#define LWIP_IPV6 0
#define LWIP_ARP 1
#define LWIP_ACD 1
#define LWIP_ETHERNET 1
#define LWIP_ICMP 1
#define LWIP_RAW 1
#define LWIP_UDP 1
#define LWIP_TCP 1
#define LWIP_DHCP 1
#define LWIP_DNS 1
#define LWIP_IGMP 0
#define LWIP_NETIF_STATUS_CALLBACK 1
#define LWIP_NETIF_LINK_CALLBACK 1
#define LWIP_NETIF_HOSTNAME 1
#define LWIP_NETIF_TX_SINGLE_PBUF 1

#define MEM_ALIGNMENT 4
#define MEM_SIZE (32 * 1024)
#define MEMP_NUM_PBUF 16
#define MEMP_NUM_UDP_PCB 8
#define MEMP_NUM_TCP_PCB 8
#define MEMP_NUM_TCP_PCB_LISTEN 4
#define MEMP_NUM_TCP_SEG 32
#define PBUF_POOL_SIZE 16
#define PBUF_POOL_BUFSIZE 1600

#define LWIP_TCP_KEEPALIVE 1
#define TCP_TTL 64
#define TCP_MSS 1460
#define TCP_WND (4 * TCP_MSS)
#define TCP_SND_BUF (4 * TCP_MSS)
#define TCP_SND_QUEUELEN 16

#define DNS_TABLE_SIZE 4
#define DNS_MAX_SERVERS 2

#define ETHARP_TABLE_SIZE 10
#define ETH_PAD_SIZE 0
#define LWIP_CHKSUM_ALGORITHM 3
#define LWIP_PROVIDE_ERRNO 1
#define DHCP_DOES_ARP_CHECK 0
#define ESP_LWIP_DHCP_FINE_TIMERS_ONDEMAND 0
#define ESP_LWIP_IGMP_TIMERS_ONDEMAND 0
#define ESP_LWIP_DNS_TIMERS_ONDEMAND 0
#define ESP_LWIP_MLD6_TIMERS_ONDEMAND 0

#endif
